# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - goconst
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2

issues:
  exclude-use-default: false
  exclude-dirs:
    - bin
    - vendor
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
