version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8000:8080
      - 50000:50000
    volumes:
      - ${HOME}/test/jenkins_configuration:/var/jenkins_home
